### ISSUE TITLE
Extension inserts full module name after entered symbols

### ISSUE THREAD

**Issue by olegdizus** [ChristianKohler/NpmIntellisense#10]
E. g. 

```
import module from 'module-module-name'
                    ^^^^^^^
                    This is entered symbols
```

**Comment by kasperekt** [comment]
It is worth mentioning that this bug only occurs when cursor is after dash char `-`. Other characters may also make this happen.

**Comment by olegdizus** [comment]
Yes, issue only occurs if i select autocomplete suggestion after dash char.
