### ISSUE TITLE
Inserting suggestion on dot key

### ISSUE THREAD

**Issue by 19majkel94** [ChristianKohler/NpmIntellisense#12]
When I want to add import/require from my own files, I use relative path starting with `.`. And the problem is that I got intellisense immediately when I'm opening quotes (`" "`) and when I press the `.` key, it enters the first suggestion.

I would be nice to have an option to set accepting suggestion only on enter or tab press

**Comment by third774** [comment]
This is supremely annoying, especially working with Angular2.

**Comment by ChristianKohler** [comment]
Look at https://github.com/ChristianKohler/PathIntellisense/issues/9 

the solution is to unbind .. Add this to keybindings.json:
{ "key": ".", "command": "" }

**Comment by third774** [comment]
Awesome, thanks! Is there a reason this isn't implemented by default?

**Comment by redstrike** [comment]
@ChristianKohler 
```
`the solution is to unbind .. Add this to keybindings.json:
 "key": ".", "command": "" }
```
I think the solution for this issue should be included in the user guide.
It's lucky for me that there aren't many issues in this project so that I can browse the closed issues.
In fact, it's difficult to search for a similar issue on Github. Even the search engine is smart enough, it still difficult to choose correct keywords to search.

**Comment by Hfahrudin** [comment]
it still didnt unbind it sadly

**Comment by verysame** [comment]
So, from my understanding adding  { "key": ".", "command": "" } should allow me to insert images to html files and VSC should add the filename and the file extension as well, i.e. filename.jpg
If that's the case, is still not working, I only get the filename but not the extension.

**Comment by yaas-dev** [comment]
I believe you can unbind this by setting `editor.acceptSuggestionOnCommitCharacter` to `false`

**Comment by samgermain** [comment]
@ChristianKohler Where is `keybindings.json` located?

**Comment by samgermain** [comment]
[Here's how to find where keybindings.json is located](https://code.visualstudio.com/docs/getstarted/keybindings#_advanced-customization)
