### ISSUE TITLE
Extension tries to autocomplete when cursor is between `import` and `from`

### ISSUE THREAD

**Issue by kasperekt** [ChristianKohler/NpmIntellisense#13]
There should be no suggestions when cursor is between `import` and `from` keywords.
Right now extension starts to show npm packages names when cursor is in this position:
```js
import React, {PropTypes, Co|} from 'react';
                            ^
```

It should only give suggestions when cursor is inside import string:

```js
import React, {PropTypes, Component} from 'rea|';
                                              ^
```

It looks like this in real life:
![example_bug](https://cloud.githubusercontent.com/assets/6966280/18869434/a0557242-84ac-11e6-9365-eb98e1c767c9.png)

I could take care of this next week. For now, I don't have much time.

**Comment by 19majkel94** [comment]
I have the same problem, when I use destructing import (`import { ClassName } from "./my-class-file"`).
It's annoying because I got VS Code intellisense about exported member to choose mixed with npm intellisense.
