### ISSUE TITLE
Add node included packages to suggestions

### ISSUE THREAD

**Issue by jens1o** [ChristianKohler/NpmIntellisense#14]
Wouldn't be cool to have a suggestion that I also be able to require `path` for example?

**Comment by ChristianKohler** [comment]
@jens1o Good Idea. Would this be this list? 

`node -pe "require('repl')._builtinLibs"`

```
[ 'assert',
  'buffer',
  'child_process',
  'cluster',
  'crypto',
  'dgram',
  'dns',
  'domain',
  'events',
  'fs',
  'http',
  'https',
  'net',
  'os',
  'path',
  'punycode',
  'querystring',
  'readline',
  'repl',
  'stream',
  'string_decoder',
  'tls',
  'tty',
  'url',
  'util',
  'v8',
  'vm',
  'zlib' ]
```

**Comment by jens1o** [comment]
I'm fine with it! Anything needed is there as I want ❤️ 

Thanks!

**Comment by jens1o** [comment]
When will the new version be released?

**Comment by ChristianKohler** [comment]
@jens1o I just released an updated version of PathIntellisense and started working on NpmIntellisense now. Can't promise anything but I hope to be able to release a new version by Tuesday morning.

**Comment by jens1o** [comment]
Okey, thanks! :)

**Comment by ChristianKohler** [comment]
v1.1.0 comes with this feature. Thank you @jens1o for the idea.

**Comment by jens1o** [comment]
Thanks too!
