### ISSUE TITLE
Use also relative path

### ISSUE THREAD

**Issue by mookraiser** [ChristianKohler/NpmIntellisense#2]
Thanks for this great plugin. Is it also possible to handle relative imports ?

import stuff from './folder/file'

note that the extension is not specified when webpack is used. It resolve it from
a config file that say it can be ".js, .jsx or whatever"

sometimes the extension is specified:
import stuff from './folder/file.less'

you could add such conf in yours, using an ordered list of file extensions.

**Comment by ChristianKohler** [comment]
Yes: Search for the plugin "Path Intellisense"

**Comment by mookraiser** [comment]
does not work, I send them a question. Thanks anyway.
