### ISSUE TITLE
Add support for: import 'module-name'

### ISSUE THREAD

**Issue by elderfo** [ChristianKohler/NpmIntellisense#25]
When importing certain modules, devs will use the `import 'module-name';` syntax. I've used it mostly while pulling in polyfills but am sure there are plenty of other use-cases. That syntax is included in the spec http://www.ecma-international.org/ecma-262/6.0/#sec-imports (see: `import ModuleSpecifier ;`)

I'll have a PR coming soon with this.

**Comment by ChristianKohler** [comment]
Added with @elderfo PR #26 and release 1.2.0
