### ISSUE TITLE
Intellisense not working after update (relative path ../)

### ISSUE THREAD

**Issue by elonmallin** [ChristianKohler/NpmIntellisense#36]
I am using this for HTML files like:
```
<link rel="import" href="../day-picker/day-picker.html">
```
After the update it doesn't find a relative path like this. It only finds files in the same folder as the current file I'm editing.

**Comment by ttugates** [comment]
Same here..  Also when you type the exact name, the auto populated dropdown seems to refresh.

Can't seem to find a downgrade for VSCode Extensions either :/

**Comment by jinglf000** [comment]
Path Intellisense v1.4.1
VScode v1.12.1

**Comment by DanaiPhi** [comment]
me too.

**Comment by hmanicka** [comment]
Experiencing the same issue. Intellisense not working after update.
VScode: v1.25.1
Path Intellisense v1.4.2

**Comment by ChristianKohler** [comment]
Closing this one since it seems to relate to Path Intellisense, not NPM Intellisense
