### ISSUE TITLE
Go to defenition (F12) doesn't apply *.es6, *.mjs, etc.

### ISSUE THREAD

**Issue by munrocket** [ChristianKohler/NpmIntellisense#59]
Steps to Reproduce:

1. Create foo.mjs:
```
    /** @param {string} name */
    export default function bar(name) {
      return 'hi'
    }
```
2. Create use-it.mjs:
```
    import bar from './foo.mjs'

    // Then...
```
3. ...type bar(
4. Go to defenition (F12) doesn't work
5. Renaming foo.mjs to foo.js all is ok.

**Comment by Yahia2** [comment]
$ npm i a11y_accordions
$ git clone https://github.com/scottaohara/a11y_accordions.git
<div data-aria-accordion>
  <h3 data-aria-accordion-heading>
    Heading Here
  </h3>
  <div data-aria-accordion-panel>
    <p>
      Content here
    </p>
  </div>
  
</div>

**Comment by ChristianKohler** [comment]
How is this related to this extension?
