### ISSUE TITLE
Suggestions missing for some file types on require

### ISSUE THREAD

**Issue by maha2490** [ChristianKohler/NpmIntellisense#66]
- Issue Type: Bug
- Extension Name: path-intellisense
- Extension Version: 1.4.2
- OS Version: Windows 10 1809
- VSCode version: 1.43

Have a unique situation where I need to require .html files within a .js file. In a require statement, only .js files are suggested. This is a static application, so we only have html, css, and js files. There might be other file types missing, but this is what I am working with atm. 

In screenshot below, I have multiple .html files under the `./profile` directory.
![all-files-not-selected](https://user-images.githubusercontent.com/18745326/77801394-27c26500-704f-11ea-9ad1-a968c67c5802.png)

**Comment by ChristianKohler** [comment]
Hey @maha2490, is think you posted this issue in the wrong extension. This is NPMIntellisense, not PathIntellisense.
