### ISSUE TITLE
Publish to Open VSX

### ISSUE THREAD

**Issue by akosyakov** [ChristianKohler/NpmIntellisense#77]
Unfortunately MS prohibits usages of MS marketplace by any other products or redistribution vsix files from it. Because of it we kindly ask you to take the ownership of your namespace in OpenVSX and publish there as well.

OpenVSX is a vendor neutral alternative to MS marketplace used by all other derivatives of VS Code like [Gitpod](gitpod.io), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), VSCodium, Theia based IDEs, and so on.

The docs for publishing the extension are here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions. Technically this should be straightforward. You get a token and call `ovsx publish` with it. For example, this is how RedHat publishes their java extension: [redhat-developer/vscode-java@ff51dbf/Jenkinsfile#L73-L82](https://github.com/redhat-developer/vscode-java/blob/5d4f8d58b8e919534800ca7bc41e8513c288f573/Jenkinsfile#L78-L82)

Let me know if you are opened to a PR contributing a release GH action both to MS marketplace and OpenVSX.

**Comment by ChristianKohler** [comment]
Hey @akosyakov 

> Let me know if you are opened to a PR contributing a release GH action both to MS marketplace and OpenVSX.

Happy to do that. I've just setup the account on OpenVSX and have a token ready 👍

**Comment by akosyakov** [comment]
@filiptronicek Could you provide a PR please? 🙏
